### ISSUE TITLE
Pathnames in registry URLs are not preserved

### ISSUE THREAD

**Issue by tomdyqin** [velut/node-query-registry#233]
eg: 
registry =  'http://registry.a.com/npm'
name = 'packageName'
request will filter '/npm' path like 'http://registry.a.com/packageName'

expect：
registry =  'http://registry.a.com/npm'
name = 'packageName'
request like 'http://registry.a.com/npm/packageName'

**Comment by velut** [comment]
Hi @tomdyqin, can you try using thi pre-release version https://www.npmjs.com/package/query-registry/v/2.3.0-0 to see if it fixes the problem for you? Thanks.

**Comment by tomdyqin** [comment]
> 

it's work~  😁

**Comment by velut** [comment]
Thanks for testing @tomdyqin.

I've published the release version `2.3.0`.
