### ISSUE TITLE
catch {} causes SyntaxError: Unexpected Token

### ISSUE THREAD

**Issue by utillity** [velut/node-query-registry#270]
````
/.../node_modules/query-registry/dist/query-registry.cjs.development.js:747
  } catch {}
          ^
SyntaxError: Unexpected token {

/usr/share/gcui/node_modules/query-registry/dist/query-registry.cjs.development.js:139
    } catch {}
SyntaxError: Unexpected token {
````

it should be `catch (err) { }` as per MDN

**Comment by velut** [comment]
Hi @utillity, thanks for opening the issue.

[On MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch), it says that the exception part can be omitted (see also their [example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#the_exception_identifier)):

> `exceptionVar` Optional
>    An optional identifier to hold the caught exception for the associated `catch` block. If the `catch` block does not utilize the exception's value, you can omit the `exceptionVar` and its surrounding parentheses, as `catch {...}`.

The optional catch binding should be well supported by vendors and tools (see [compatibility data](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#browser_compatibility)).

Can you share some details about how you are getting the error (tools, Node or browser version, commands used) ?

**Comment by utillity** [comment]
Hi, I am using this library with node 8.9.3 on an embedded device (unfortunately I can't install a newer node version there). if you want to make it backward-compatible that would be great :)

I'm just using `getPackageManifest({ name: packageName, registry: registry })` from your library

**Comment by utillity** [comment]
uff, looks like there are a couple of issues blocking me from using your library with node 8.9.3 - don't need to fix the catch :)

**Comment by velut** [comment]
That's unfortunate, what are the other issues if you don't mind? Maybe you could try compiling (part of) the library for your use case or use something like [patch-package](https://www.npmjs.com/package/patch-package) in your install step.

If you want to implement something yourself to fetch manifests from npm the endpoints look like this `https://registry.npmjs.org/<bare name or scoped name>/<version or tag>`, for example https://registry.npmjs.org/query-registry/2.6.0 or https://registry.npmjs.org/@types/node/latest.

**Comment by utillity** [comment]
this old nodejs version also doesn't support Object.fromEntries. I could pull and try to get everything working, if you need it. I found a simple workaround which works for me - I just use fetch() to get the JSON directly from my private repository, so no dependencies needed :)

**Comment by velut** [comment]
I see. Don't worry about the PR, supporting older versions is not a priority right now and I plan to use features available in current and future releases anyway (like native `fetch`).

I'm glad you found a solution that works for you.
